apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-wm6o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-wm6o
    app.kubernetes.io/part-of: test-rhtap-15-app
  name: devfile-sample-code-with-quarkus-wm6o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-wm6o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-wm6o
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-15-tenant/test-rhtap-15-app/devfile-sample-code-with-quarkus-wm6o@sha256:e9c8cc94ada12764d8247b41043c34264db328296a108cbb1dc1cfd0d4aa903d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
